package studentGUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class StudentProfile extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private String[] columns = {"NAME", "STUDENT ID", "IC NO", "EMAIL", "PHONE NO", "ROOM TYPE"};
    private int row;

    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
        model.setColumnIdentifiers(columns);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMainTitle = new javax.swing.JLabel();
        lCommand = new javax.swing.JLabel();
        lStudentID = new javax.swing.JLabel();
        lCommand1 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProfile = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lMainTitle.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        lMainTitle.setText("Student Profile");

        lCommand.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lCommand.setText("Enter the student ID that");

        lStudentID.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lStudentID.setText("Student ID : ");

        lCommand1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lCommand1.setText("You Want To View > ");

        btnSearch.setBackground(new java.awt.Color(165, 144, 127));
        btnSearch.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(110, 74, 48));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tableProfile.setModel(model);
        tableProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableProfileMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableProfile);

        btnBack.setBackground(new java.awt.Color(165, 144, 127));
        btnBack.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(103, 103, 103)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lCommand1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(btnSearch))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lCommand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCommand1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStudentID)
                    .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(45, 45, 45)
                .addComponent(lMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchStudentID = tID.getText(); // Get the student ID from the input field or text box
        String statusFile = "reservationData.txt";

        if (searchStudentID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a student ID to perform the search.");
            return; // Exit the method if the student ID is empty
        }

        try (BufferedReader br = new BufferedReader(new FileReader(statusFile))) {
            String studentName;
            String studentID;
            String IC;
            String email;
            String phoneNo;
            String roomtype;
            boolean found = false;

            // Initialize the table model
            while ((studentName = br.readLine()) != null
                    && (studentID = br.readLine()) != null
                    && (IC = br.readLine()) != null
                    && (email = br.readLine()) != null
                    && (phoneNo = br.readLine()) != null
                    && (roomtype = br.readLine()) != null) {
                if (studentID.equals(searchStudentID)) {
                    // Add student information to the table model
                    model.addRow(new Object[]{studentName, studentID, IC, email, phoneNo, roomtype});
                    tID.setText("");
                    found = true;
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(null, "No student record found with the given ID.");
            }
            tableProfile.setModel(model);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableProfileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProfileMouseReleased
        // TODO add your handling code here:
        int selectedRowIndex = tableProfile.getSelectedRow();
        if (selectedRowIndex != -1) {
            String studentName = tableProfile.getValueAt(selectedRowIndex, 0).toString();
            String studentID = tableProfile.getValueAt(selectedRowIndex, 1).toString();
            String IC = tableProfile.getValueAt(selectedRowIndex, 1).toString();
            String email = tableProfile.getValueAt(selectedRowIndex, 1).toString();
            String phoneNo = tableProfile.getValueAt(selectedRowIndex, 1).toString();
            String roomtype = tableProfile.getValueAt(selectedRowIndex, 1).toString();
        }
    }//GEN-LAST:event_tableProfileMouseReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        TrackApplication track = new TrackApplication();
        track.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCommand;
    private javax.swing.JLabel lCommand1;
    private javax.swing.JLabel lMainTitle;
    private javax.swing.JLabel lStudentID;
    private javax.swing.JTextField tID;
    private javax.swing.JTable tableProfile;
    // End of variables declaration//GEN-END:variables
}
